{
    Geometry: parseGeometry(curElmnt['st_astext']),
    Fund_St: curElmnt['funding_status'],
    Legacy_ID: curElmnt['uid_12'],
    Lead_Ag: null,
    Proj_Title: curElmnt['project_ti'],
    Proj_Ty: null,
    Proj_Desc: curElmnt['scope__sum'],
    Contact_info: {
          Contact_info_name: "TBD",
          Contact_info_phone: "TBD",
          Contact_info_email: "TBD"
        },
    More_info: curElmnt['other_info'],
    Primary_Street: curElmnt['primary_st'],
    Cross_Streets: [curElmnt['cross_stre'], curElmnt['cross_st_1']],
    Proj_Status: curElmnt['current_st'],
    Proj_Man: curElmnt['project_ma'],
    CD: curElmnt['cd'],
    Access: curElmnt['accessibil'],
    Dept_Proj_ID: curElmnt[' dept_proj_'],
    Other_ID: curElmnt['other_proj'],
    Total_bgt: curElmnt['bgt_total'],
    Grant: curElmnt['grant_'],
    Other_funds: curElmnt['other_fund'],
    Prop_c: curElmnt['prop_c'],
    Measure_r: curElmnt['measure_r'],
    Gas_Tax: curElmnt['gas_tax'],
    General_fund: curElmnt['general_fu'],
    Authorization: curElmnt['authorizat'],
    Issues: curElmnt['issues'],
    Deobligation: curElmnt['at_risk_of'],
    Explanation: curElmnt['explain_if'],
    Constr_by: curElmnt['constructi'],
    Info_source: curElmnt['source'],
    Grant_Cat: null,
    Grant_Cycle: null,
    Est_Cost: null,
    Fund_Rq: null,
    Lc_match: curElmnt['total_local_match'],
    Match_Pt: null
}