INSERT INTO "Projects" ( 
 "Geometry",
 "Proj_Title",
 "Dept_Proj_ID",
 "Proj_Desc",
 "Primary_Street",
 "Total_bgt",
 "Grant",
 "Other_funds",
 "Prop_c",
 "Measure_r", 
 "Gas_Tax",
 "General_fund", 
 "Authorization",
 "More_info",
 "Proj_Status",
 "CD", 
 "Deobligation",
 "Explanation",
 "Proj_Man", 
 "Other_ID",
 "Proj_Ty",
 "Lc_match",
 "Fund_St"
 )
SELECT 
 wkb_geometry as Geometry,
 project_ti as Proj_Title,
 dept_proj_ as Dept_Proj_ID,
 scope__sum as Proj_Desc,
 primary_st as Primary_Street,
 bgt_total as Total_bgt,
 "grant" as "Grant",
 other_fund as Other_funds,
 prop_c as Prop_c,
 measure_r as Measure_r, 
 gas_tax as Gas_Tax,
 general_fu as General_fund, 
 authorizat as "Authorization",
 other_info as More_info,
 current_st as Proj_Status,
 cd as CD, 
 at_risk_of as Deobligation,
 explain_if as Explanation,
 project_ma as Proj_Man, 
 uid as Other_ID,	
 project_category as Proj_Ty,
 total_local_match as Lc_match,
 funding_status as Fund_St
FROM ogrgeojson;